### ISSUE TITLE
Cassandra version 3.11.0 is not available

### ISSUE THREAD

**Issue by praveen049** [andrewrothstein/ansible-cassandra#2]
Hi
  In the  defaults file
```
# defaults file for ansible-cassandra
cassandra_ver : '3.11.0'
cassandra_mirror : http://www-us.apache.org/dist/cassandra
cassandra_checksums:
  '3.11.0': sha256:d597b99b402bd2cf925033519db9e58340acb893fd83d600d904ba4041d44fa7
  '3.11.1': sha256:6feed696759e2f3219e0ebde13f4c9080cac0744a77eb3cb43af136ab527f0ed
cassandra_install_parent_dir : /usr/local
cassandra_download_timeout_seconds: 600
```
the cassandra version is mapped to 3.11.0; but this version is currently not available on the mirror configured in the defaults files. 
This causes  below failure:
fatal: [192.168.0.14]: FAILED! => {"changed": false, "dest": "/tmp/apache-cassandra-3.11.0-bin.tar.gz", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://www-us.apache.org/dist/cassandra/3.11.0/apache-cassandra-3.11.0-bin.tar.gz"}

**Comment by andrewrothstein** [comment]
indeed. it looks like that mirror only has the most recent two patch releases. I upgraded the role to default to v3.11.2 which is present on the main distribution site and published to the galaxy as v2.0.5. feel free to choose a more appropriate mirror for yourself with Ansible vars.
