### ISSUE TITLE
Cannot start cassandra

### ISSUE THREAD

**Issue by praveen049** [andrewrothstein/ansible-cassandra#3]
Hi
   I am able to successfully run the cassandra role.

But after the execution of playbook when i login to the server and try to start cassandra, i get the below error

`cassandra@spark-1-3:~$ Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file /usr/local/cassandra/bin/../logs/gc.log due to No such file or directory
WARN  [main] 2018-03-20 05:30:01,972 StartupChecks.java:332 - Directory /usr/local/cassandra/bin/../data/data doesn't exist
ERROR [main] 2018-03-20 05:30:01,973 CassandraDaemon.java:708 - Has no permission to create directory /usr/local/cassandra/bin/../data/data
`

But when i try to start cassandra as root with -R option it works.

I am running the playbook as -u option set to cassandra user.

Can you please comment what i am doing wrong ?

Thans

**Comment by andrewrothstein** [comment]
this role merely installs cassandra. you need to configure cassandra appropriately for your use case. consider the andrewrothstein.cassandra-cluster role.
